### ISSUE TITLE
'Done' is always False for all environments

### ISSUE THREAD

**Issue by agakshat** [openai/multiagent-particle-envs#10]
Is there any particular reason why the `_step(self,action_n)` function in `environment.py` just returns `False` for `done_n` for all agents, irrespective of what is happening in the environment? 
Makes it very difficult to train MADDPG, because initially the agents just keep going out of the environment (the render window), and while I believe the environment should return `done=True` in this case, allowing the training to reset and start over, it just keeps going - making it difficult to learn IMO.

Another question is why are the environments not bounded?

**Comment by ryan-lowe** [comment]
Hi,
The nature of the current environments is that they are unbounded (mostly for convenience), and this is how we trained our models in the paper (but you should get the same behaviour either way --- it may just take a bit longer to train). I've added support for a done_callback in `environment.py` if you wanted to make a new version of the environment where the episode terminates if an agent leaves the screen (you'll have to implement a `check_done()` function in the new scenario, and then pass in `scenario.check_done` when instantiating `MultiAgentEnv`).
