### ISSUE TITLE
Is done() function necessary? When to finish episode?

### ISSUE THREAD

**Issue by yakotaki** [openai/multiagent-particle-envs#13]
Should done function return true only when agent is out of range?

`     def done(self, agent, world):`
`        x = abs(agent.state.p_pos[0])`
`        y = abs(agent.state.p_pos[1])`
`        if (x > 1.0 or y > 1.0):`
`            return True`
`        return False   `
Or I also should add condition for terminating episode when goal is reached?

Thanks and sorry, I'm newbie here.

**Comment by ryan-lowe** [comment]
Hi! In general, we don't actually use the `done` function in our experiments --- we let the agents explore off-screen, and if they reach the target then we let them keep going (in case they later veer away from the landmark). This makes the scenarios harder for the agents.

Feel free to add your own custom `done` functions in any new scenarios that you create, but note that these will produce different results.
