### ISSUE TITLE
Example traing code?

### ISSUE THREAD

**Issue by watts4speed** [openai/multiagent-particle-envs#15]
Hi,

Is there an example somewhere that shows how to train using the baselines implementations for DDPG or other system?  Could you give a few pointers on what I'd have to do to try the baselines algorithm implementations on your environment?

I was wondering also environment did you originally train in?

Thanks in advance.

**Comment by yakotaki** [comment]
Check here [https://github.com/rohan-sawhney/multi-agent-rl](https://github.com/rohan-sawhney/multi-agent-rl)

**Comment by ryan-lowe** [comment]
We now have publicly available training code here:
https://github.com/openai/maddpg
