### ISSUE TITLE
problem with gym version >= 0.10

### ISSUE THREAD

**Issue by yakotaki** [openai/multiagent-particle-envs#17]
Hi, problem seems to be related to version of gym used for multiagent-particle-envs.
Every time when I'm using methods of env like reset or render I'm getting this error.

```
    states = env.reset()
  File "/home/yakotaki/Downloads/gym-master/gym/core.py", line 71, in reset
    raise NotImplementedError
NotImplementedError

```
after downgrading gym to any ver < 0.10 error disappear

**Comment by watts4speed** [comment]
I still found I need to fix up the code to get it to run after a reorganization was done on the OpenAI code at the end of January.  Sorry I’m answering from my phone otherwise I’d send a code sample.

**Comment by danbri** [comment]
I'm seeing something similar,

````
(gyms) -bash-3.2$ bin/interactive.py --scenario simple.py
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "bin/interactive.py", line 23, in <module>
    env.render()
  File "/Users/danbri/anaconda3/envs/gyms/lib/python3.6/site-packages/gym/core.py", line 111, in render
    raise NotImplementedError
NotImplementedError

**Comment by ryan-lowe** [comment]
Thanks for raising this issue! I'll talk to the folks at OpenAI to see if we can resolve it.

**Comment by ryan-lowe** [comment]
Pushed some code that should fixed the issue (removed underscores in _step, _render, etc.). Let me know if problems persist!
