### ISSUE TITLE
TypeError: render() got an unexpected keyword argument 'close'

### ISSUE THREAD

**Issue by nanxintin** [openai/multiagent-particle-envs#20]
Hi, when I tried to run the interative.py, I came across some errors:
"
Traceback (most recent call last):
  File "interactive.py", line 21, in <module>
    env = MultiAgentEnv(world, scenario.reset_world, scenario.reward, scenario.observation, info_callback=None, shared_viewer = False)
  File "/home/shao/projects-py2/rl/multiagent-particle-envs/bin/../multiagent/environment.py", line 68, in __init__
    self.observation_space.append(spaces.Box(low=-np.inf, high=+np.inf, shape=(obs_dim,), dtype=np.float32))
TypeError: __init__() got an unexpected keyword argument 'dtype'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/shao/projects-py2/gym/gym/utils/closer.py", line 67, in close
    closeable.close()
  File "/home/shao/projects-py2/gym/gym/core.py", line 164, in close
    self.render(close=True)
TypeError: render() got an unexpected keyword argument 'close'
"
I tried to reinstall the gym, but it also failed.
I would appreciate it if anyone could help me.

**Comment by nanxintin** [comment]
Update the gym and the error will be solved.

**Comment by arisliang** [comment]
I encounter same issue with gym 0.10.4, what version of gym have you updated to to resolve this issue?

**Comment by nanxintin** [comment]
@arisliang I solved this issue with gym 0.10.3.

**Comment by roboserg** [comment]
doesnt solve the issue for me with 0.10.3

**Comment by jaskarannagi19** [comment]
@nanxintin 
Hey Pal 
Same issue here how do i solve I am running latest build
