### ISSUE TITLE
execute the scenerios in windows command 

### ISSUE THREAD

**Issue by sanshibayuan** [openai/multiagent-particle-envs#25]
when I executed 
python bin/interactive.py -s simple_push.py
It only showed 2 empty windows
The only scenerio that worked is simple.py 
How can I solve this ?

**Comment by jaskarannagi19** [comment]
@sanshibayuan  How did you solved this

**Comment by sanshibayuan** [comment]
I downgraded pyglet to 1.2.0 and solve this issue

**Comment by ZhangShaungnj** [comment]
I down my pyglet to 1.2.0 but an error appears(ㄒoㄒ)
AttributeError: module 'time' has no attribute 'clock'
