### ISSUE TITLE
Undefined name: 'reward' in simple_speaker_listener.py

### ISSUE THREAD

**Issue by cclauss** [openai/multiagent-particle-envs#27]
__reward__ is an undefined name in [this context](https://github.com/openai/multiagent-particle-envs/blob/master/multiagent/scenarios/simple_speaker_listener.py#L60).  Should it be __self.reward__ instead?

flake8 testing of https://github.com/openai/multiagent-particle-envs on Python 3.6.3

$__flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./multiagent/scenarios/simple_speaker_listener.py:60:16: F821 undefined name 'reward'
        return reward(agent, reward)
               ^
./multiagent/scenarios/simple_speaker_listener.py:60:30: F821 undefined name 'reward'
        return reward(agent, reward)
                             ^
2     F821 undefined name 'reward'
2
```

**Comment by ryan-lowe** [comment]
Thanks! Should be fixed in the latest commit.
