### ISSUE TITLE
reward of simple_reference

### ISSUE THREAD

**Issue by nicoring** [openai/multiagent-particle-envs#28]
The reward for the `simple_reference` scenario is defined as follows:
```python
def reward(self, agent, world):
    if agent.goal_a is None or agent.goal_b is None:
        return 0.0
    dist2 = np.sum(np.square(agent.goal_a.state.p_pos - agent.goal_b.state.p_pos))
    return -dist2
```
So every agent is rewarded based on the performance of the other agent, but shouldn't be the reward be the sum of both agents' rewards? For example, something like:

```python
def reward(self, agent, world):
    reward = 0.0
    for agent in world.agents:
        if agent.goal_a is None or agent.goal_b is None:
            continue
        reward -= np.sum(np.square(agent.goal_a.state.p_pos - agent.goal_b.state.p_pos))
    return reward
```
In the first case, the agents have no direct incentive to move towards the goal because they only get rewarded if the other agent is close to their goal, but in the second case every agent is incentivised to communicate the goal to the other agent and to move toward its own goal.
So wouldn't be a shared reward more appropriate or is this a desired challenge which algorithms have to overcome?

**Comment by ryan-lowe** [comment]
Hi! This is a great point -- normally, this should be resolved by the `self.shared_reward` flag in `environment.py`, which automatically shares the reward amongst all agents. For some reason this was set to `False` --- I've now fixed this by adding a `world.collaborative` flag for the scenarios where `shared_reward` should be set to true.
