### ISSUE TITLE
Fixed frame for entire environment

### ISSUE THREAD

**Issue by rosewang2008** [openai/multiagent-particle-envs#36]
Hi, I was wondering whether there's a feature to have a single, fixed frame rendering the entire environment (as shown in your demo video in [this](https://blog.openai.com/learning-to-cooperate-compete-and-communicate/) blog post), rather that individual windows rendering each agent's view for the interactive mode. 

Thanks!

**Comment by marwanihab** [comment]
Hello, may I ask did you ever reach a solution for this issue? If you have may you please tell me what have you done? 
Thanks!

**Comment by rosewang2008** [comment]
This was some time ago, but if I recall correctly their environment.render() displays a frame per agent only for `simple.py` with user interaction on. There's a way to disable the multiple frames from being rendered and for fixing the frame location [here](https://github.com/openai/multiagent-particle-envs/blob/master/multiagent/environment.py#L247).

**Comment by ZhangShaungnj** [comment]
Do you remember how did you change the environment.render() (●'◡'●)
