### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by NorthernWolf** [openai/multiagent-particle-envs#5]
When I use command `bin/interactive.py --scenario simple.py`, it turns out an error:
```
 /Users/salse/Dropbox/openai/multiagent-particle-envs/multiagent/environment.py(149)_set_action()
    148             import ipdb; ipdb.set_trace()
--> 149             action = [action]
    150 
```
The `action` seems undefined.

Also, could you give a example of training? I even don't know what to feed in `env.step()`. A single integer or a list of integer seems doesn't work.

**Comment by hot-cheeto** [comment]
I am getting the same thing. By any way were you able to solve this ?

**Comment by hot-cheeto** [comment]
Hello, I am having trouble as well with this. By any chance were you able to figure it out ?

**Comment by ryan-lowe** [comment]
Wasn't getting that particular bug (action is received as input into _set_action() in line 135) but I fixed some other bugs and it should work now. Apologies for the confusion.

We're working on cleaning up some code for training. In the meantime, there's an open-source MADDPG implementation here:

https://github.com/xuehy/pytorch-maddpg
