### ISSUE TITLE
MultiDiscreteAction appended elements not used

### ISSUE THREAD

**Issue by tessavdheiden** [openai/multiagent-particle-envs#75]
Hi!

In the environment.py a moving and/or speaking action is executed. If an agent has both, they are not executed. In [this piece of code](https://github.com/openai/multiagent-particle-envs/blob/69ee7f85811c77ee651722bc3c332677b2195da1/multiagent/environment.py#L153), actions are appended, and in the function only action[0] is used. 

Is it true that the environment does not work with agents that both talk and move?

**Comment by Kimonili** [comment]
Hi @tessavdheiden, did you find the answer on that?

**Comment by tessavdheiden** [comment]
Hi @Kimonili, yes, please look at this [piece](https://github.com/openai/multiagent-particle-envs/blob/69ee7f85811c77ee651722bc3c332677b2195da1/multiagent/environment.py#L182). 
Here you see that an action is substituted with only the last part of itself. 
You know what I mean? First part is used for agent.action.u, second part for agent.action.c

**Comment by Kimonili** [comment]
Yes @tessavdheiden I see. So its possible for an agent to be able to speak and move as well. The thing is that when run this code:
`env.action_space[agent_with_MultiDiscrete2_action_space].n` I get an error. My code structure is such that I need to know the number of actions for each agent.

**Comment by tessavdheiden** [comment]
Where is this line?
