### ISSUE TITLE
Would you please shown us an example of how to run the basic experiment to help understand the algorithm ?

### ISSUE THREAD

**Issue by wangxiao5791509** [openai/multiagent-particle-envs#8]
Hi, as the tilte shows, would you please shown us an example of how to run the basic experiment to help understand the algorithm ?

**Comment by marwanihab** [comment]
Did you reach any example of this ?

**Comment by anshumanvenkatesh** [comment]
You can try this repo: https://github.com/openai/maddpg which links to the current repo to train agents in various scenarios
